  <div class='footer'>
    <hr/>
    <p><br/></p>
    <p class='footer' style='text-align:center;'>
      [ <a href='<?php echo $siteurl; ?>'>Main</a> ] &mdash;
      [ <a href='search.php'>Search</a> ] &mdash;
      [ <a href='assist.php'>Contribute</a> ] &mdash; 
      [ <a href='coding.php'>API</a> ] &mdash; 
      [ <a href='source.php' <?php echo $newwindow; ?>>Source Code</a> ]
      <br/><br/>
      <img src='<?php echo $siteurl; ?>/images/cc_text.png' alt='Creative Commons License' title='CC-BY-SA 3.0' style='width:10px' /> <?php echo date('Y'); ?> Philip Kahn &amp; <a href='http://www.velociraptorsystems.com'>Velociraptor Systems</a>
      &nbsp;&mdash;&nbsp;
      <a href='http://validator.w3.org/check?uri=referer' class='hidden'>XHTML 1.1</a>
      &nbsp;&mdash;&nbsp;

      <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/us/" <?php echo $newwindow; ?>>
	<img alt="Creative Commons License" style="border-width:0;border:none;vertical-align:middle;" src="http://i.creativecommons.org/l/by-sa/3.0/us/80x15.png" />
      </a>
      <br />
      <!--
      <span style='font-size:7pt;display:none;'>This 
	<span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dc:title" rel="dc:type">
	  Compiled Family-Level Phylogeny
	</span> 
	by 
	<a xmlns:cc="http://creativecommons.org/ns#" href="http://phylogeny.revealedsingularity.net" property="cc:attributionName" rel="cc:attributionURL">
	  Philip L Kahn
	</a> 
	is licensed under a 
	<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/us/">
	  Creative Commons Attribution-Share Alike 3.0 United States License
	</a>.
	<br />Based on a work at 
	<a xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://phylogeny.revealedsingularity.net" rel="dc:source">
	  phylogeny.revealedsingularity.net
	</a>.
	<br/>  
	This code is left intact for more detailed licensing instructions. Please contact me if you have any questions.
      </span>
      -->
    </p>
  </div>
