<?php
global $siteurl,$site_title,$newwindow,$superbreak,$footcount,$citecount,$citedisp,$footdisp,$siteurl,$pagetitle,$artdir,$arttext;

include("globalfunctions.inc");

$site_title='Family Phylogenetic Tree';
$siteurl='http://phylogeny.revealedsingularity.net';
$newwindow="onclick='window.open(this.href); return false;' onkeypress='window.open(this.href); return false;'";
$superbreak="<p><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/></p>";

?>